stages:
  - build
  - test

build_model:
  stage: build
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "Запускаем обучение модели..."
    - python ml_pipeline.py
  artifacts:
    paths:
      - requirements.txt
      - ml_pipeline.py

test_model:
  stage: test
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "Проверяем выполнение ML-пайплайна..."
    - python ml_pipeline.py
